config/routes.rb
# frozen_string_literal: true

# Authentication should be done from the outside
ICA::Admin::Engine.routes.draw do
  resources :carparks, controller: 'admin/carparks'
end

app/models/ica/carpark.rb
# frozen_string_literal: true

module ICA
  # Represents a {ParkingGarage}
  class Carpark < ICA::ApplicationRecord
    has_paper_trail class_name: ICA::Version.to_s

    belongs_to :parking_garage, class_name: ICA.parking_garage_class.to_s
    belongs_to :garage_system, class_name: 'ICA::GarageSystem', inverse_of: :carparks

    validates :parking_garage, presence: true
    validates :garage_system, presence: true

    delegate :name, to: :parking_garage, prefix: true

    # We don't use any internal identifiers for external communication
    validates :carpark_id, presence: true, uniqueness: { scope: :garage_system_id }
    scope :for_client, -> (client_id) do
      joins(:garage_system).merge ::ICA::GarageSystem.with_client_id(client_id)
    end
  end
end

app/controllers/ica/admin/carparks_controller.rb
# frozen_string_literal: true

module ICA::Admin
  # Configures the settings required for each parking garage
  class CarparksController < ICA::Admin::ApplicationController
    before_action :load_carpark, except: %i[new create index]

    def index
      respond_to do |format|
        format.json do
          render json: CarparksTable.new(view_context)
        end
        format.html
      end
    end

    def new
      if ICA::ParkingGarageService.unconfigured_parking_garages.any?
        @carpark = ICA::Carpark.new
      else
        flash[:alert] = 'There are no unconfigured parking garages with type ICA'
        redirect_to action: :index
      end
    end

    def create
      @carpark = ICA::Carpark.create(carpark_params)
      if @carpark.save
        redirect_to carpark_path(@carpark)
      else
        render(action: :new, status: 422)
      end
    end

    def destroy
      @carpark.destroy!
    end

    def update
      @carpark.attributes = carpark_params
      @carpark.save
      render action: :show
    end

    def show; end

    protected

    SETTINGS_PARAM = 'carpark'
    PERMITTED_ATTRIBUTES = %i[parking_garage_id carpark_id garage_system_id].freeze
    def carpark_params
      params.require(SETTINGS_PARAM).permit(*PERMITTED_ATTRIBUTES)
    end

    def load_carpark
      @carpark = ICA::Carpark.find(params[:id])
    end
  end
end

app/views/ica/admin/carparks/index.html.slim
table.table.table-condensed.table-hover.declarative-table#ica-carparks[data={ 'source' => carparks_path(format: :json), 'default-order' => '0,desc' }]
  thead
    tr
      th data={ column: {'data' => 'parking_garage_name', 'searchable' => 1, 'orderable' => 1 }} Parkhaus
      th data={ column: {'data' => 'carpark_id', 'searchable' => 1, 'orderable' => 1, link: "#{carparks_path}/:id"}} data-column-link-data='id' Objekt
  tbody

= link_to 'Neues Parkhaus einrichten', new_carpark_path, class: 'btn btn-primary'

app/views/ica/admin/carparks/new.html.slim
h1 Configure parking garage for the ICA API

= simple_form_for(@carpark, url: carparks_path) do |f|
  = f.association :parking_garage, collection: ICA::ParkingGarageService.unconfigured_parking_garages, label_method: :name, value_method: :id, prompt: 'Select a parking garage'
  = f.association :garage_system
  = f.input :carpark_id
  = f.button :submit, class: 'btn-primary'

app/views/ica/admin/carparks/show.html.slim
h1 Configuration for #{@carpark.parking_garage_name}

= simple_form_for(@carpark) do |f|
  = f.input :carpark_id
  .btn-toolbar
    .btn-group = f.button :submit, class: 'btn btn-primary'
    .btn-group = link_to 'Back to overview', carparks_path, class: 'btn btn-default'